services:
  - type: web
    name: silviagro
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn miweb.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: miweb.settings
